apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/FourtyNight/K3S_NFS_Storage_provisioner.git'  # ЗАМЕНИТЕ
    targetRevision: HEAD
    path: charts/nfs-provisioner
    helm:
      valueFiles:
        - values.yaml
      # Если нужно принудительно обновить зависимости:
      # values: |
      #   nfs-server-provisioner:
      #     persistence:
      #       storageClass: "-"
      # ...
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
