apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<ваш-username>/<репозиторий>.git'  # ЗАМЕНИТЕ
    targetRevision: HEAD
    path: charts/nfs-server
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
