apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-{{ include "nfs-storage.fullname" . }}-0
  labels:
    {{- include "nfs-storage.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}
  # Если вы хотите использовать конкретный StorageClass для данных NFS
  # storageClassName: local-path   # можно задать в values
