# Настройки для подчарта nfs-server-provisioner
nfs-server-provisioner:
  persistence:
    enabled: true
    storageClass: "-"        # используем существующий статический PV (не создаём новый)
    size: 10Gi

  storageClass:
    defaultClass: true       # сделать StorageClass стандартным
    name: nfs               # имя StorageClass (можно изменить)

  nodeSelector:
    kubernetes.io/hostname: node1   # замените на имя вашей ноды

  # tolerations:             # если нужны
  #   - key: "CriticalAddonsOnly"
  #     operator: "Exists"
  #     effect: "NoSchedule"

  # Дополнительные параметры
  #image:
   #  repository: ganesa/nfs-ganesha
    # tag: v4.0.0s
