# Размер хранилища
storageSize: 10Gi

# Путь на хосте, куда будут сохраняться данные
hostPath: /srv/volumes/data-nfs-server-provisioner-0

# Имя PVC, которое будет создано провижинером (должно совпадать)
pvcName: data-nfs-server-provisioner-0

# Namespace, в котором будет создан PVC (тот же, где будет работать провижинер)
pvcNamespace: nfs
